@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

title Компонентная диаграмма для "Surveillance Service"
Container(api, "Api Gateway", "Оркестратор для распределения запросов по доменам")
ContainerDb(common_db, "Common Database", "PostgreSQL", "Хранит данные сервисов (данные пользователя, дома, состояния устройств, телеметрию)", $tags = "storage")

Container_Boundary(gate, "Surveillance Service") {
    Component(surveillance_controller, "Surveillance API Controller", "Предоставляет REST API для управления камерами видеонаблюдения")
    Component(surveillance_management, "Surveillance Manager", "Управляет камерами видеонаблюдения")
    Component(surveillance_monitor, "Surveillance Monitor", "Обрабатывает данные видео с камер видеонаблюдения")
    Component(surveillance_repository, "Surveillance Repository", "Слой взаимодействия с БД")
    Rel(surveillance_controller, surveillance_management, "Использует")
    Rel(surveillance_controller, surveillance_monitor, "Использует")
    Rel(surveillance_management, surveillance_repository, "Использует")
    Rel(surveillance_monitor, surveillance_repository, "Использует")
}

Rel(api, surveillance_controller, "Использует", "JSON/HTTPS")
Rel(surveillance_repository, common_db, "Читает из/ записывает в [SQL]")
@enduml